### ISSUE TITLE
BUG? sql IN operator only works with a list of two values

### ISSUE THREAD

**Issue by la-bell** [zbrookle/sql_to_ibis#65]
`SELECT * FROM mytable WHERE mycolumn IN ('value1', 'value2')` works fine, but if I have more than two values within the parentheses, `InvalidQueryException` is raised. The typical use of `IN` should allow for n comparison values. Am I misunderstanding something in composing my query or is there a workaround for this operator to use more than two values? Thanks!

**Comment by zbrookle** [comment]
@la-bell Yeah that's definitely a bug, should be fixed soon
